---
- name: ensure supervisord is installed
  pip:
    name=supervisor
    state=present
  tags: supervisord

- name: ensure directories are created
  file:
    state=directory
    dest={{ item }}
    mode=0755
  with_items:
    - "{{ supervisord_log_dir }}"
    - "{{ supervisord_programs_dir }}"
  tags: supervisord

- name: setup configuration
  template:
    src=supervisord.conf.j2
    dest=/etc/supervisord.conf
  tags: supervisord

# BEGIN Init
- name: setup CentOS supervisord service script
  copy:
    src=supervisord_centos
    dest=/etc/init.d/supervisord
    owner=root
    group=root
    mode=0755
  tags: supervisord
  when: ansible_os_family == "RedHat" and ansible_service_mgr != "systemd"

- name: setup Ubuntu supervisord service script (init)
  copy:
    src=supervisord_ubuntu
    dest=/etc/init.d/supervisord
    owner=root
    group=root
    mode=0755
  tags: supervisord
  when: ansible_os_family == "Debian" and ansible_service_mgr != "systemd"
# END Init

# BEGIN Systemd
- name: setup Debian supervisord service script (systemd)
  copy:
    src=supervisord_ubuntu_systemd_service
    dest=/etc/systemd/system/supervisord.service
    owner=root
    group=root
    mode=0755
  tags: supervisord
  when: ansible_os_family == "Debian" and ansible_service_mgr == "systemd"

- name: setup RedHat supervisord service script (systemd)
  copy:
    src=supervisord_centos_systemd_service
    dest=/etc/systemd/system/supervisord.service
    owner=root
    group=root
    mode=0755
  tags: supervisord
  when: ansible_os_family == "RedHat" and ansible_service_mgr == "systemd"
# END Systemd

- name: ensure CentOS daemon is restarted
  shell: systemctl daemon-reload
  tags: supervisord
  when: ansible_os_family == "RedHat"

- name: ensure supervisord is enabled
  service:
    name: supervisord
    enabled: yes
  tags: supervisord

- name: ensure supervisord is running
  service:
    name: supervisord
    state: started
  tags: supervisord

- name: reload supervisor (init)
  shell: "supervisorctl reload"
  tags: supervisord
  when: ansible_service_mgr != "systemd"

- name: reload supervisor (systemd)
  shell: "systemctl reload supervisord.service"
  tags: supervisord
  when: ansible_service_mgr == "systemd"

- name: set up sc alias
  lineinfile: dest="/root/.bashrc" line="alias sc='supervisorctl'"

